version: '3.8'

services:
  echo-db:
    image: postgres:15-alpine
    container_name: echo_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: EchoTicketDb
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - echo_pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: echo_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always

  redis:
    image: redis
    container_name: echo_redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  echo_pgdata: