version: '3.8'

services:
  echo-db:
    image: postgres:15-alpine
    container_name: echo_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456 
      POSTGRES_DB: EchoTicketDb
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - echo_pgdata:/var/lib/postgresql/data

volumes:
  echo_pgdata: